version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/Monal/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/rust/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "daily"
