name: Check PR title for proper semver

on:
  pull_request:
    branches:
      - beta
      - stable

jobs:
  check-pr-semver-title:
    runs-on: ubuntu-latest
    name: Validate PR Title

    steps:
      - name: Check PR title format
        run: |
          version="${{ github.event.pull_request.title }}"
          if ! [[ "$version" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
            echo "Invalid semver: '$version'!"
            exit 1
          fi
          echo "Version is proper semver: $version"
 
